server:
  port: 8003
spring:
  application:
    name: serviceb
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.80.7:1521:orcl
      username: scott
      password: tiger
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/