spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.30:3306/hotword?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
      username: hotword
      password: hotword@2018
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  aop:
    #使用CGLIB动态代理织入增强
    proxy-target-class: true

logging:
  level:
    com:
      ddssoft:
        hotwordbase:
          mapper: debug
        hotwordsearch:
          dao: debug